name: Mirror a wheel to a ssh server
description: Mirror a wheel to a ssh server
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  name:
    description: Name of package being irrored
    required: true
  input_dir:
    description: Input directory of wheels
    required: false
    default: ${{ github.workspace }}/dist
  output_dir:
    description: Output directory to place the wheels that will be mirrored
    required: false
    default: ${{ github.workspace }}/wheels
  ssh_host:
    description: Server to sync to
    required: true
  ssh_key:
    description: Key to use
    required: true
  ssh_dir:
    description: Path to sync to
    required: true
  ssh_user:
    description: User to authenticate as
    required: true
runs:
  using: composite
  steps:
    - name: Create directories
      shell: bash
      run: |
        python -u "${{ github.action_path }}"create_dirs.py \
          "${{ inputs.input_dir }}" \
          "${{ inputs.output_dir }}"
    - name: Sync with wheels.eeems.codes
      shell: bash
      run: |
        if ! [ -z "$(ls -A "${{ inputs.input_dir }}")" ]; then
          touch "$KEY_LOCATION"
          chmod 600 "$KEY_LOCATION"
          echo "$SSH_KEY" > "$KEY_LOCATION"
          rsync \
            -Pcuav \
            -e "ssh -p 22 -oStrictHostKeyChecking=no -i \"$KEY_LOCATION\"" \
            "${{ inputs.output_dir }}"/* \
            "$SSH_USER@$SSH_HOST:$SSH_DIR/"
          rm "$KEY_LOCATION"
        fi;
      env:
        KEY_LOCATION: ${{ runner.temp }}/server_key
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_DIR: ${{ inputs.ssh_dir }}
        SSH_USER: ${{ inputs.ssh_user }}
