name: "Build wheel for pypi package"
description: Build a wheel for a pypi package
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  name:
    description: Package name to build
    required: true
  output_dir:
    description: Output directory to place the wheels
    required: false
    default: ${{ github.workspace }}/dist
  python_version:
    description: Python version to use
    required: false
    default: "3.13"
    type: choice
    options:
      - "3.14"
      - "3.13"
      - "3.12"
      - "3.11"
      - "3.10"
      - "3.9"
  build_on:
    description: Build target to use
    required: false
    default: "ubuntu-amd64"
    type: choice
    options:
      - ubuntu-amd64
      - debian-armv7l
      - manylinux-armv7l-glibc
      - manylinux-armv7l-musl
      - manylinux-aarch64-glibc
      - manylinux-aarch64-musl
      - manylinux-x86_64-glibc
      - manylinux-x86_64-musl
      - manylinux-i686-glibc
      - manylinux-i686-musl
      - manylinux-s390x-glibc
      - manylinux-s390x-musl
      - manylinux-ppc64le-glibc
      - manylinux-ppc64le-musl
      - manylinux-riscv64-glibc
      - manylinux-riscv64-musl
  setup:
    description: Setup script to run building the package
    required: false
    default: ""
  config_settings:
    description: Extra configuration options to pass to the backend
    required: false
    default: "null"
runs:
  using: composite
  steps:
    - name: Set up QEMU
      if: inputs.build_on != 'ubuntu-amd64'
      uses: docker/setup-qemu-action@v4
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.build_on == 'ubuntu-amd64' && inputs.python_version || '3.11' }}
    - name: Build Wheel
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        set -e
        python -u "${{ github.action_path }}/action.py" \
          --workspace="${{ inputs.output_dir  }}" \
          --build_on="${{ inputs.build_on  }}" \
          --python="${{ inputs.python_version  }}" \
          "${{ inputs.name }}" \
      env:
        SETUP: ${{ inputs.setup }}
        CONFIG_SETTINGS: ${{ inputs.config_settings }}
