name: "Build wheel for pypi package"
description: Build a wheel for a pypi package
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  name:
    description: Package name to build
    required: true
  output_dir:
    description: Output directory to place the wheels
    required: false
    default: ${{ github.workspace }}/dist
  python_version:
    description: Python version to use
    required: false
    default: "3.13"
    type: choice
    options:
      - "3.14"
      - "3.13"
      - "3.12"
      - "3.11"
      - "3.10"
      - "3.9"
  build_on:
    description: Build target to use
    required: false
    default: "ubuntu-amd64"
    type: choice
    options:
      - ubuntu-amd64
      - debian-armv7l
      - manylinux-armv7l-glibc
      - manylinux-armv7l-musl
      - manylinux-aarch64-glibc
      - manylinux-aarch64-musl
      - manylinux-x86_64-glibc
      - manylinux-x86_64-musl
      - manylinux-i686-glibc
      - manylinux-i686-musl
      - manylinux-s390x-glibc
      - manylinux-s390x-musl
      - manylinux-ppc64le-glibc
      - manylinux-ppc64le-musl
      - manylinux-riscv64-glibc
      - manylinux-riscv64-musl
  setup:
    description: Setup script to run building the package
    required: false
    default: ""
  config_settings:
    description: Extra configuration options to pass to the backend
    required: false
    default: "null"
runs:
  using: composite
  steps:
    - name: Set up QEMU
      if: inputs.build_on == 'debian-armv7l' || startsWith(inputs.build_on, 'manylinux-')
      uses: docker/setup-qemu-action@v4
    - name: Build Wheel
      if: startsWith(inputs.build_on, 'manylinux-')
      shell: bash
      run: |
        set -e
        if [ -n "$RUNNER_DEBUG" ];then
          set -x
        fi
        arch=$(echo "${{inputs.build_on }}" | cut -d'-' -f2)
        if [[ "${{ inputs.build_on }}" == *"-musl" ]];then
          image="musllinux_1_2_$arch"
        elif [[ "$arch" == "armv7l" ]];then
          image="manylinux_2_35_$arch"
        elif [[ "$arch" == "riscv64" ]];then
          image="manylinux_2_39_$arch"
        else
          image="manylinux_2_34_$arch"
        fi
        docker run \
          --privileged \
          --rm \
          tonistiigi/binfmt --install all
        docker run \
          --rm \
          -v "${src_path}":/workspace \
          -v "${{ github.action_path }}":/action \
          -e RUNNER_DEBUG="$RUNNER_DEBUG" \
          -e UNIVERSAL="$UNIVERSAL" \
          -e MANYLINUX="$image" \
          -e CONFIG_SETTINGS="$CONFIG_SETTINGS" \
          -e SETUP="$SETUP" \
          quay.io/pypa/"$image":latest \
          bash -ec "$script"
      env:
        src_path: ${{ inputs.output_dir }}
        CONFIG_SETTINGS: ${{ inputs.config_settings }}
        SETUP: ${{ inputs.setup }}
        script: |
          if [ -n "$RUNNER_DEBUG" ];then
            set -x
          fi
          echo 'Installing requirements'
          python=${{ inputs.python_version }}
          python_interpreter=cp${python//./}-cp${python//./}
          manylinux-interpreters ensure "${python_interpreter}"
          PATH="/opt/python/${python_interpreter}/bin:$PATH"
          cat > ~/.pypirc << EOF
            [distutils]
            index-servers =
                pypi
                eeems

            [pypi]

            [eeems]
            repository = https://wheels.eeems.codes/
          EOF
          cd /tmp
          echo 'Building'
          python -u /action/build.py "${{ inputs.name }}" "/workspace"
          if [ -f /workspace/*.whl ];then
            auditwheel repair /workspace/*.whl
            rm -f /workspace/*.whl
            mv wheelhouse/*.whl /workspace/
          fi
    - name: Build Wheel
      if: inputs.build_on == 'debian-armv7l'
      shell: bash
      run: |
        docker run \
          --rm \
          --platform=linux/arm/v7 \
          -v "${src_path}":/workspace \
          -v "${{ github.action_path }}":/action \
          -e RUNNER_DEBUG="$RUNNER_DEBUG" \
          -e UNIVERSAL="$UNIVERSAL" \
          -e CONFIG_SETTINGS="$CONFIG_SETTINGS" \
          -e SETUP="$SETUP" \
          eeems/nuitka-arm-builder:bullseye-${{ inputs.python_version }} \
          bash -ec "$script"
      env:
        src_path: ${{ inputs.output_dir }}
        CONFIG_SETTINGS: ${{ inputs.config_settings }}
        SETUP: ${{ inputs.setup }}
        script: |
          echo 'Installing requirements'
          cat > ~/.pypirc << EOF
            [distutils]
            index-servers =
                pypi
                eeems

            [pypi]

            [eeems]
            repository = https://wheels.eeems.codes/
          EOF
          source /opt/lib/nuitka/bin/activate
          cd /tmp
          echo 'Building'
          python -u /action/build.py "${{ inputs.name }}" "/workspace"
    - uses: actions/setup-python@v6
      if: inputs.build_on == 'ubuntu-amd64'
      with:
        python-version: ${{ inputs.python_version }}
    - name: Build Wheel
      if: inputs.build_on == 'ubuntu-amd64'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        echo 'Installing requirements'
        cat > ~/.pypirc << EOF
          [distutils]
          index-servers =
              pypi
              eeems

          [pypi]

          [eeems]
          repository = https://wheels.eeems.codes/
        EOF
        echo 'Building'
        python -u "${{ github.action_path }}/build.py" "${{ inputs.name }}" "${{ inputs.output_dir  }}"
      env:
        SETUP: ${{ inputs.setup }}
        CONFIG_SETTINGS: ${{ inputs.config_settings }}
